fix: allow publishing with no version in config file (#868)
https://github.com/dsherret/jsr-publish-on-tag/actions/runs/12332179143/job/34419677355

```
$ deno publish --set-version 0.2.0
Download https://registry.npmjs.org/@types/node/-/node-18.16.19.tgz
Check file:///home/runner/work/jsr-publish-on-tag/jsr-publish-on-tag/src/main.ts
Checking for slow types in the public API...
Check file:///home/runner/work/jsr-publish-on-tag/jsr-publish-on-tag/src/main.ts
Publishing @david/publish-on-tag@0.2.0 ...
error: Failed to publish @david/publish-on-tag@0.2.0
Caused by:
    Failed to publish @david/publish-on-tag at 0.2.0: invalid config file '/deno.json': missing field `version`
Error: Process completed with exit code 1.
```